version: '3.1'
services:
  app:
    container_name: credit-application-system
    image: credit-application
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1552_1552
      - POSTGRES_USER=postgres
      - POSTGRES_DB=CreditApplicationSystem