
DROP TABLE IF EXISTS credit_application_result;
DROP TABLE IF EXISTS credit_application;
DROP TABLE IF EXISTS customer_credit_score;
DROP TABLE IF EXISTS customer;


CREATE TABLE customer
(
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
identity_number VARCHAR(11) NOT NULL UNIQUE,
firstname VARCHAR(50) NOT NULL,
lastname VARCHAR(50) NOT NULL,
salary NUMERIC(15,2) NOT NULL,
phone VARCHAR(15) NOT NULL,
create_date DATE DEFAULT CURRENT_DATE,
update_date DATE DEFAULT CURRENT_DATE
);

CREATE TABLE customer_credit_score
(
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
credit_score INT NOT NULL,
customer_id INT NOT NULL,
FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE credit_application
(
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
application_status INT NOT NULL DEFAULT 0,
create_date DATE DEFAULT CURRENT_DATE,
update_date DATE DEFAULT CURRENT_DATE,
customer_id INT NOT NULL,
FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE credit_application_result
(
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
credit_limit NUMERIC(15,2) DEFAULT 0,
credit_result VARCHAR(5) NOT NULL,
create_date DATE DEFAULT CURRENT_DATE,
credit_application_id INT NOT NULL,
FOREIGN KEY (credit_application_id) REFERENCES credit_application(id)
);



INSERT INTO customer (identity_number,firstname,lastname,salary,phone,create_date,update_date)
            VALUES ('12345678912','Pınar','Özdil',5500.00,'05397607208',CURRENT_DATE,CURRENT_DATE),
                   ('98765432121','Bihter','Özdil',9500.00,'05326609908',CURRENT_DATE,CURRENT_DATE),
                   ('52369874156','Lale','Özdil',4500.00,'05367896532',CURRENT_DATE,CURRENT_DATE),
                   ('14725836914','Furkan','Demir',10000.00,'05391237224',CURRENT_DATE,CURRENT_DATE);

INSERT INTO customer_credit_score(credit_score,customer_id)
            VALUES (420,1),
                   (500,2),
                   (1000,3),
                   (2000,4);

INSERT INTO credit_application(application_status,create_date,update_date,customer_id)
            VALUES (0,CURRENT_DATE,CURRENT_DATE,1);